version: '3'
services:
  # API Server
  server:
    container_name: sorasvl-server
    build:
      context: ./server
    depends_on:
      - mongo
    volumes:
      - ./server:/workdir
      - /workdir/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
    networks:
      - sorasvl

  # Client
  client:
    container_name: sorasvl-client
    build:
      context: ./client
    depends_on:
      - server
    networks:
      - sorasvl
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start

  # Nginx
  nginx:
    container_name: sorasvl-router
    build:
      context: ./nginx
    depends_on:
      - server
      - client
    ports:
      - '80:80'
    networks:
      - sorasvl

  # MongoDB
  mongo:
    container_name: sorasvl-mongo
    volumes:
      - ./mongo/data:/data/db
    build:
      context: ./mongo
    ports:
      - '28018:27017'
    networks:
      - sorasvl

networks:
  sorasvl:
    driver: bridge
